modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Create-Technomancy/Technomancy/issues"
[[mods]]
modId="technomancy"
version="${file.jarVersion}"
displayName="Create: Technomancy"
#updateJSONURL="https://raw.githubusercontent.com/Create-Technomancy/Technomancy/main/update.json" # if you ever decide to implement update checking uncomment this line
displayURL="https://github.com/Create-Technomancy/Technomancy"
logoFile="icon.png"
credits="rdh"
authors="Cosmos616, The_seVen_, Chazbomb"
description='''
Using magical energy to advance science, Create-Style!
'''
[[dependencies.technomancy]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.d,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.5-91,)"
    ordering="AFTER"
    side="CLIENT"
