modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="technomancy" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create: Technomancy" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="technomancy.png" #optional
credits="" #optional
authors="Cosmos616, The_seVen_, Chazbomb" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
???
'''
[[dependencies.technomancy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.d,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.5-91,)"
    ordering="AFTER"
    side="CLIENT"
