modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Create-Technomancy/Technomancy/issues"

[[mods]]
modId="technomancy"
version="${file.jarVersion}"
displayName="Create: Technomancy"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="technomancy.png"
credits=""
authors="Cosmos616, The_seVen_, CHAZBOMB1"
description='''
???
'''
[[dependencies.technomancy]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.d,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.5-91,)"
    ordering="AFTER"
    side="CLIENT"
