modLoader="javafml"
loaderVersion="[${forge},)"
license="MIT"
issueTrackerURL="https://github.com/Create-Technomancy/Technomancy/issues"

[[mods]]
modId="technomancy"
version="${file.jarVersion}"
displayName="Create: Technomancy"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
credits="DrMangoTea, Cak, rdh, The_seVen_"
authors="CHAZBOMB1"
description='''
Employ magic as an alternative to all things technical.
'''

[[dependencies.technomancy]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.technomancy]]
    modId="create"
    mandatory=true
    versionRange="[${create},)"
    ordering="NONE"
    side="BOTH"